name: mfswd62b_cpd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  camera: ^0.11.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.5.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  objectbox: ^5.1.0
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  objectbox_generator: any

flutter:
  uses-material-design: true
